### ISSUE TITLE
TODO: refactor

### ISSUE THREAD

**Issue by nfour** [nfour/serverless-build-plugin#33]
- [x] Maintain full backward compat for serverless 1.0
- [x] Deprecate 0.5 support in @1.0 of this plugin, remove in @2.0
- [x] Rewrite in typescript
- [ ] Add more tests
- [x] Add travis build system and publishing
- [ ] Build typescript docs for the options objects via d.ts files
